# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20161020_0228'),
        ('video', '0003_auto_20161019_1340'),
    ]

    operations = [
    ]
