# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_merge_20161024_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
    ]
