# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=models.CharField(default='01040117166', max_length=50),
            preserve_default=False,
        ),
    ]
