# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20161020_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_facebook_user',
            new_name='is_facebook_users',
        ),
    ]
