# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20161021_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_facebook_users',
            new_name='is_facebook_user',
        ),
    ]
