# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20161021_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='01040117166', max_length=50),
            preserve_default=False,
        ),
    ]
