# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsrank',
            name='friends_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
