# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20161025_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Album',
            new_name='album',
        ),
        migrations.AlterField(
            model_name='photo',
            name='dislike_users',
            field=models.ManyToManyField(default=0, related_name='photo_set_dislike_users', through='photo.PhotoDisLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='like_users',
            field=models.ManyToManyField(default=0, related_name='photo_set_like_users', through='photo.PhotoLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
